### ISSUE TITLE
Build libXNVCtrl for the next release?

### ISSUE THREAD

**Issue by guihkx** [flathub/com.valvesoftware.Steam.Utility.MangoHud#1]
Hey there.

The next MangoHud release will add support for [querying GPU usage in older NVIDIA GPUs](https://github.com/flightlessmango/MangoHud/issues/3), such as 600 and 700 series. Because these GPUs don't have support in [NVML](https://developer.nvidia.com/nvidia-management-library-nvml), the devs added a fallback method that uses [libXNVCtrl](https://github.com/NVIDIA/nvidia-settings/tree/master/src/libXNVCtrl).

It's a very small library, so I was hoping you could include it in this Flatpak build. Arch Linux packages it as a separate library, so if you need help building it, [here's the build script](https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/nvidia-settings) they use.

If you also need help testing it, I'll gladly help, since I have one these old GPUs.

Thank you!

**Comment by gasinvein** [comment]
Thanks for the info. Will libXNVCtrl be compatible with older/newer driver versions?

**Comment by gasinvein** [comment]
In any case, I guess it should be added to Steam bundle instead, if @nanonyme doesn't mind.

**Comment by guihkx** [comment]
>Will libXNVCtrl be compatible with older/newer driver versions?

I think so, yes. 

If I understand correctly, this lib communicates with the current NVIDIA driver using some X extension provided by NVIDIA. I've seen some projects on GitHub still using outdated versions of it, so I think it should be backwards/forwards compatible.
