### ISSUE TITLE
Where do I find the config file?

### ISSUE THREAD

**Issue by okseb** [flathub/com.valvesoftware.Steam.Utility.MangoHud#12]
According to the default installation instructions ([here](https://github.com/flightlessmango/MangoHud#hud-configuration)) it'd be at `$HOME/.config/MangoHud/MangoHud.conf`

Where can I find this file in the Flatpak extension?

**Comment by gasinvein** [comment]
In the Steam flatpak app config directory, `~/.var/app/com.valvesoftware.Steam/config/MangoHud/MangoHud.conf`

**Comment by okseb** [comment]
I had checked there, the config folder under the com.valvesoftware.Steam folder doesn't exist for me should I just create it?

**Comment by gasinvein** [comment]
Yes, you can create it there, or do `flatpak override --user --filesystem=xdg-config/MangoHud:ro com.valvesoftware.Steam` to give Steam flatpak app access to MangoHud config on the host.
