### ISSUE TITLE
Can't load the new version after EOL

### ISSUE THREAD

**Issue by Taulim** [flathub/com.valvesoftware.Steam.Utility.MangoHud#15]
I'm sure that I'm missing something really simple and this will be a silly question, but there we go...

I received the EOL warning this morning and decided to uninstall this package and re-install the rebased one (org.freedesktop.Platform.VulkanLayer.MangoHud), however I cannot see how to load this package inside the Steam flatpak runtime.

Is there something I need to set or is it something still needed on the Freedesktop / Steam flatpak side?

**Comment by gasinvein** [comment]
Basically you just set `MANGOHUD=1` environment variable and that's it.
If for some reason you prefer the `mangohud` command - it's located at `/usr/lib/extensions/MangoHud/bin/mangohud`.

**Comment by gasinvein** [comment]
Yes, I've just noted that the extension landed on the wrong branch, should've been `21.08` instead of `stable`. I've submitted a build to correct branch, please install `MangoHud//21.08` once it's available.

**Comment by Taulim** [comment]
Amazing, thank you!
