### ISSUE TITLE
32 bits support?

### ISSUE THREAD

**Issue by nahuel3pro** [flathub/com.valvesoftware.Steam.Utility.MangoHud#20]
Please, could you update the software so it supports 32bits games? Thx.

**Comment by gasinvein** [comment]
This flatpak is obsolete, install `org.freedesktop.Platform.VulkanLayer.MangoHud//21.08` instead.
And it should work fine for 32bit. If not, report it with some more details (e.g. which game, how it's launched) [here](https://github.com/flathub/org.freedesktop.Platform.VulkanLayer.MangoHud/issues).
