### ISSUE TITLE
App not showing in FlatHub!

### ISSUE THREAD

**Issue by heidiwenger** [flathub/com.valvesoftware.Steam.Utility.MangoHud#21]
"App Not Found

No app with the ID com.valvesoftware.Steam.Utility.MangoHud was found on Flathub. Try searching for the app using the search bar above."

https://flathub.org/apps/details/com.valvesoftware.Steam.Utility.MangoHud

**Comment by heidiwenger** [comment]
The thread about the creation of flatpak was here: https://discourse.flathub.org/t/goverlay-and-mangohud-added-together-in-flatpak-for-very-convenient-use-the-developer-needs-help-on-this/532

**Comment by gasinvein** [comment]
Flathub web frontend doesn't support extensions, so not showing MangoHud is expected.

Also note this extension is end-of-life for a long time and replaced by `org.freedesktop.Platform.VulkanLayer.MangoHud`.
